baseURL = 'https://eugenejyuan.github.io/'
languageCode = 'en-us'
title = "Jing Yuan"  # Change to your name or preferred site title

[author]
  name = "Jing Yuan"
  homepage = "https://eugenejyuan.github.io"

# Theme configuration
[module]
  [[module.imports]]
    path = 'github.com/yihui/hugo-xmin'

# Site parameters
[params]
  footer = "&copy; Jing Yuan 2024-{Year}"
  description = "Jing Yuan's personal website - Research, Blog and Projects"
  keywords = ["Jing Yuan", "Research", "Blog", "Projects", "Personal Website"]
  author = "Jing Yuan"
  # Social media
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/eugenejyuan"
  # Open Graph
  [params.opengraph]
    image = "/images/og-image.jpg"
    type = "website"
  # Twitter Cards
  [params.twitter]
    card = "summary_large_image"
    site = "@yourtwitterhandle"
    creator = "@yourtwitterhandle"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
