baseURL = 'https://eugenejyuan.github.io/'
languageCode = 'en-us'
title = "Jing Yuan"  # Change to your name or preferred site title

[author]
  name = "Jing Yuan"
  homepage = "https://eugenejyuan.github.io"

# Theme configuration
[module]
  [[module.imports]]
    path = 'github.com/yihui/hugo-xmin'

# Site parameters
[params]
  footer = "&copy; Jing Yuan {Year}"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
